### ISSUE TITLE
 Failed to import "nonebot_plugin_alicdk_get"

### ISSUE THREAD

**Issue by cy920820** [Kaguya233qwq/nonebot2-plugin-AliCDK-get#2]
为什么使用 `nb plugin install` 安装之后， `nb run` 会报错呢

**Comment by Kaguya233qwq** [comment]
请提供详细的错误日志供我排查问题

**Comment by Kaguya233qwq** [comment]
> 为什么使用 `nb plugin install` 安装之后， `nb run` 会报错呢
请提供详细的错误日志供我排查问题

**Comment by cy920820** [comment]
![image](https://user-images.githubusercontent.com/21211512/192965930-173ec8eb-b894-4358-b319-c1a3dfffc420.png)

**Comment by cy920820** [comment]
前后就用了两个命令
`nb plugin install`

`nb run`

**Comment by Kaguya233qwq** [comment]
你没有配置群组id，你需要在env文件里配置。我的文档里有写的。

**Comment by cy920820** [comment]
> 你没有配置群组id，你需要在env文件里配置。我的文档里有写的。

和这个 Error `Failed to import "nonebot_plugin_alicdk_get"` 有关联吗？ 
不过我确实还没配 .env,

**Comment by cy920820** [comment]
必须要配置群组？机器人QQ不行么？

**Comment by Kaguya233qwq** [comment]
所有的命令目前都在群组执行。所以要填群号。你可以建一个专门的测试群

**Comment by Kaguya233qwq** [comment]
另外pip刚刚更新了1.1版本。你可以upgrade一下

**Comment by cy920820** [comment]
有机会我加你 QQ 沟通吧

**Comment by Kaguya233qwq** [comment]
> 

好的
